name: Dev NPM
on: pull_request
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  deploy-to-dev-npm-branch:
    name: Deploy to `npm` branch
    needs: ci
    if: contains(github.event.pull_request.labels.*.name, 'dev-npm')
    uses: ./.github/workflows/deploy-artifact-as-branch.yml
    with:
      environment: npm-branch
      artifact_name: npmDist
      target_branch: dev-npm
      commit_message: "Deploy ${{github.event.workflow_run.head_sha}} to 'npm' branch"
